import { readFileSync } from 'node:fs'; import { join } from 'node:path';
import type { OnlineLobbyMessage, OnlineLobbySnapshot } from '../../../online/types';
import { CREATE_PLAYER_OPTIONS, CREATE_TIMER_OPTIONS, DEFAULT_ONLINE_LOBBY, calculatedBotSlots, currentLobbyPlayer, dedupeMessages, isLobbyHost, startBlockReason, validateChatBody } from '../onlineLobbyModel';
const players=(count:number,ready=true)=>Array.from({length:count},(_,i)=>({lobbyId:'l',userId:`u${i}`,seatIndex:i,displayName:`P${i}`,ready,joinedAt:''}));
const lobby=(patch:Partial<OnlineLobbySnapshot>={}):OnlineLobbySnapshot=>({id:'l',code:'ABC123',hostUserId:'u0',name:null,visibility:'private',status:'waiting',maxPlayers:4,turnTimerSeconds:0,botSlots:0,botFillEnabled:false,createdAt:'',updatedAt:'',players:players(2),...patch});
describe('Stage 5C lobby contract',()=>{
 it('CREATE_LOBBY_DEFAULTS and product choices',()=>{expect(DEFAULT_ONLINE_LOBBY).toEqual({visibility:'public',maxPlayers:4,turnTimerSeconds:0,botFillEnabled:false});expect(CREATE_PLAYER_OPTIONS).toEqual([2,3,4,5,6]);expect(CREATE_TIMER_OPTIONS).toEqual([0,15,30,60]);});
 it('identifies host and stable seat order',()=>{const value=lobby();expect(isLobbyHost(value,'u0')).toBe(true);expect(currentLobbyPlayer(value,'u1')?.seatIndex).toBe(1);expect(isLobbyHost(value,'u1')).toBe(false);});
 it('requires all humans ready and host actor',()=>{expect(startBlockReason(lobby(),'u0')).toBeNull();expect(startBlockReason(lobby({players:players(2,false)}),'u0')).toContain('готовы');expect(startBlockReason(lobby(),'u1')).toContain('организатора');});
 it('requires two humans without bots but permits ready solo bot fill',()=>{expect(startBlockReason(lobby({players:players(1)}),'u0')).toContain('2 игрока');expect(startBlockReason(lobby({players:players(1),botFillEnabled:true}),'u0')).toBeNull();expect(calculatedBotSlots(lobby({players:players(1),botFillEnabled:true}))).toBe(3);});
 it('starting blocks actions in UI start model',()=>expect(startBlockReason(lobby({status:'starting'}),'u0')).toContain('запускается'));
 it('validates chat boundaries and deduplicates by id',()=>{expect(validateChatBody(' ')).toBeNull();expect(validateChatBody('x'.repeat(280))).toHaveLength(280);expect(validateChatBody('x'.repeat(281))).toBeNull();const m=(id:number):OnlineLobbyMessage=>({id,lobbyId:'l',userId:'u',displayName:'P',body:'x',createdAt:''});expect(dedupeMessages([m(2),m(1),m(2)]).map(x=>x.id)).toEqual([1,2]);});
 it('migration contains bot fill, authoritative start, chat RLS and realtime',()=>{const sql=readFileSync(join(process.cwd(),'supabase/migrations/20261001143130_stage5c_real_online_lobby.sql'),'utf8');for(const text of ['bot_fill_enabled boolean not null default false','status=\'starting\'','all human players must be ready','online_lobby_messages enable row level security','send_online_lobby_message','alter publication supabase_realtime add table public.online_lobby_messages'])expect(sql).toContain(text);expect(sql).toContain('v_humans >= v_max');expect(sql).toContain('update public.online_lobby_players set ready=false');});
 it('ready API uses the serialized RPC and realtime exposes cleanup',()=>{const api=readFileSync(join(process.cwd(),'src/online/lobbyApi.ts'),'utf8');const implementation=api.match(/export async function setReady[\s\S]*?\n}/)?.[0]??'';expect(implementation).toContain("rpc('set_online_lobby_ready'");expect(implementation).toContain('p_lobby_id: lobbyId');expect(implementation).toContain('p_ready: ready');expect(implementation).not.toContain("from('online_lobby_players')");expect(implementation).not.toContain('.update(');const realtime=readFileSync(join(process.cwd(),'src/online/realtime.ts'),'utf8');expect(realtime).toContain('removeChannel(channel)');});
});
