import type { CardDefinition } from './types';

/** Manual visual audit of the user-supplied archive, cards 051..100.
 * Topology edge order: N=0, E=1, S=2, W=3.
 * Expansion/edition badges are not scoring shields.
 */
export const AUDITED_051_100: readonly CardDefinition[] = [
  { id:'card-051', asset:'1 (51).jpg', edges:{north:'city',east:'city',south:'city',west:'field'}, topology:{roads:[],cities:[[0,1,2]],cityShields:[0]}, shields:0 },
  { id:'card-052', asset:'1 (52).jpg', edges:{north:'road',east:'city',south:'city',west:'city'}, topology:{roads:[[0]],cities:[[1,2,3]],cityShields:[0]}, shields:0 },
  { id:'card-053', asset:'1 (53).jpg', edges:{north:'field',east:'river',south:'field',west:'river'}, topology:{roads:[],cities:[],riverEdges:[1,3]}, shields:0, riverCard:true, riverKind:'middle' },
  { id:'card-054', asset:'1 (54).jpg', edges:{north:'city',east:'river',south:'city',west:'river'}, topology:{roads:[],cities:[[0],[2]],cityShields:[0,0],riverEdges:[1,3]}, shields:0, riverCard:true, riverKind:'middle' },
  { id:'card-055', asset:'1 (55).jpg', edges:{north:'river',east:'river',south:'city',west:'city'}, topology:{roads:[],cities:[[2,3]],cityShields:[0],riverEdges:[0,1]}, shields:0, riverCard:true, riverKind:'middle' },
  { id:'card-056', asset:'1 (56).jpg', edges:{north:'city',east:'field',south:'city',west:'city'}, topology:{roads:[],cities:[[0,2,3]],cityShields:[1]}, shields:1 },
  { id:'card-057', asset:'1 (57).jpg', edges:{north:'road',east:'city',south:'city',west:'city'}, topology:{roads:[[0]],cities:[[1,2,3]],cityShields:[0]}, shields:0 },
  { id:'card-058', asset:'1 (58).jpg', edges:{north:'road',east:'field',south:'road',west:'city'}, topology:{roads:[[0,2]],cities:[[3]],cityShields:[0]}, shields:0 },
  { id:'card-059', asset:'1 (59).jpg', edges:{north:'field',east:'field',south:'city',west:'field'}, topology:{roads:[],cities:[[2]],cityShields:[0]}, shields:0 },
  { id:'card-060', asset:'1 (60).jpg', edges:{north:'field',east:'field',south:'city',west:'field'}, topology:{roads:[],cities:[[2]],cityShields:[0]}, shields:0 },
  { id:'card-061', asset:'1 (61).jpg', edges:{north:'field',east:'field',south:'field',west:'field'}, topology:{roads:[],cities:[]}, shields:0 },
  { id:'card-062', asset:'1 (62).jpg', edges:{north:'road',east:'road',south:'city',west:'city'}, topology:{roads:[[0,1]],cities:[[2,3]],cityShields:[0]}, shields:0 },
  { id:'card-063', asset:'1 (63).jpg', edges:{north:'field',east:'field',south:'field',west:'field'}, topology:{roads:[],cities:[],monastery:true}, shields:0 },
  { id:'card-064', asset:'1 (64).jpg', edges:{north:'road',east:'city',south:'road',west:'city'}, topology:{roads:[[0,2]],cities:[[1,3]],cityShields:[1]}, shields:1 },
  { id:'card-065', asset:'1 (65).jpg', edges:{north:'road',east:'road',south:'field',west:'road'}, topology:{roads:[[0],[1],[3]],cities:[]}, shields:0 },
  { id:'card-066', asset:'1 (66).jpg', edges:{north:'road',east:'road',south:'city',west:'road'}, topology:{roads:[[0,1,3]],cities:[[2]],cityShields:[0]}, shields:0 },
  { id:'card-067', asset:'1 (67).jpg', edges:{north:'river',east:'road',south:'river',west:'road'}, topology:{roads:[[1,3]],cities:[],riverEdges:[0,2]}, shields:0, riverCard:true, riverKind:'middle' },
  { id:'card-068', asset:'1 (68).jpg', edges:{north:'field',east:'road',south:'field',west:'road'}, topology:{roads:[[1,3]],cities:[]}, shields:0 },
  { id:'card-069', asset:'1 (69).jpg', edges:{north:'city',east:'road',south:'road',west:'city'}, topology:{roads:[[1,2]],cities:[[0,3]],cityShields:[0]}, shields:0 },
  { id:'card-070', asset:'1 (70).jpg', edges:{north:'city',east:'city',south:'road',west:'road'}, topology:{roads:[[2,3]],cities:[[0,1]],cityShields:[0]}, shields:0 },
  { id:'card-071', asset:'1 (71).jpg', edges:{north:'city',east:'road',south:'road',west:'city'}, topology:{roads:[[1,2]],cities:[[0,3]],cityShields:[0]}, shields:0 },
  { id:'card-072', asset:'1 (72).jpg', edges:{north:'road',east:'road',south:'field',west:'road'}, topology:{roads:[[0],[1],[3]],cities:[]}, shields:0 },
  { id:'card-073', asset:'1 (73).jpg', edges:{north:'field',east:'road',south:'field',west:'road'}, topology:{roads:[[1,3]],cities:[],monastery:true}, shields:0 },
  { id:'card-074', asset:'1 (74).jpg', edges:{north:'city',east:'road',south:'road',west:'city'}, topology:{roads:[[1,2]],cities:[[0,3]],cityShields:[0]}, shields:0 },
  { id:'card-075', asset:'1 (75).jpg', edges:{north:'city',east:'city',south:'city',west:'city'}, topology:{roads:[],cities:[[0,1],[2,3]],cityShields:[0,0]}, shields:0 },
  { id:'card-076', asset:'1 (76).jpg', edges:{north:'road',east:'city',south:'road',west:'city'}, topology:{roads:[[0,2]],cities:[[1],[3]],cityShields:[0,0]}, shields:0 },
  { id:'card-077', asset:'1 (77).jpg', edges:{north:'road',east:'city',south:'field',west:'road'}, topology:{roads:[[0,3]],cities:[[1]],cityShields:[0]}, shields:0 },
  { id:'card-078', asset:'1 (78).jpg', edges:{north:'road',east:'road',south:'road',west:'road'}, topology:{roads:[[0],[1],[2],[3]],cities:[]}, shields:0 },
  { id:'card-079', asset:'1 (79).jpg', edges:{north:'river',east:'road',south:'river',west:'city'}, topology:{roads:[[1]],cities:[[3]],cityShields:[0],riverEdges:[0,2]}, shields:0, riverCard:true, riverKind:'middle' },
  { id:'card-080', asset:'1 (80).jpg', edges:{north:'city',east:'city',south:'field',west:'city'}, topology:{roads:[],cities:[[0,1,3]],cityShields:[1]}, shields:1 },
  { id:'card-081', asset:'1 (81).jpg', edges:{north:'field',east:'field',south:'field',west:'field'}, topology:{roads:[],cities:[],monastery:true}, shields:0 },
  { id:'card-082', asset:'1 (82).jpg', edges:{north:'city',east:'city',south:'city',west:'city'}, topology:{roads:[],cities:[[0,1,2,3]],cityShields:[2]}, shields:2 },
  { id:'card-083', asset:'1 (83).jpg', edges:{north:'field',east:'city',south:'city',west:'city'}, topology:{roads:[],cities:[[1,2,3]],cityShields:[0]}, shields:0 },
  { id:'card-084', asset:'1 (84).jpg', edges:{north:'road',east:'city',south:'road',west:'city'}, topology:{roads:[[0,2]],cities:[[1,3]],cityShields:[1]}, shields:1 },
  { id:'card-085', asset:'1 (85).jpg', edges:{north:'field',east:'city',south:'city',west:'city'}, topology:{roads:[],cities:[[1,2,3]],cityShields:[0]}, shields:0 },
  { id:'card-086', asset:'1 (86).jpg', edges:{north:'road',east:'city',south:'road',west:'city'}, topology:{roads:[[0,2]],cities:[[1],[3]],cityShields:[0,0]}, shields:0 },
  { id:'card-087', asset:'1 (87).jpg', edges:{north:'city',east:'city',south:'city',west:'road'}, topology:{roads:[[3]],cities:[[0,1,2]],cityShields:[1]}, shields:1 },
  { id:'card-088', asset:'1 (88).jpg', edges:{north:'river',east:'road',south:'road',west:'river'}, topology:{roads:[[1,2]],cities:[],riverEdges:[0,3]}, shields:0, riverCard:true, riverKind:'middle' },
  { id:'card-089', asset:'1 (89).jpg', edges:{north:'road',east:'road',south:'road',west:'road'}, topology:{roads:[[0],[1],[2],[3]],cities:[]}, shields:0 },
  { id:'card-090', asset:'1 (90).jpg', edges:{north:'river',east:'road',south:'road',west:'river'}, topology:{roads:[[1,2]],cities:[],riverEdges:[0,3]}, shields:0, riverCard:true, riverKind:'middle' },
  { id:'card-091', asset:'1 (91).jpg', edges:{north:'field',east:'river',south:'river',west:'field'}, topology:{roads:[],cities:[],riverEdges:[1,2]}, shields:0, riverCard:true, riverKind:'middle' },
  { id:'card-092', asset:'1 (92).jpg', edges:{north:'field',east:'field',south:'city',west:'city'}, topology:{roads:[],cities:[[2,3]],cityShields:[0]}, shields:0 },
  { id:'card-093', asset:'1 (93).jpg', edges:{north:'city',east:'city',south:'city',west:'city'}, topology:{roads:[],cities:[[0,3],[1,2]],cityShields:[0,1]}, shields:1 },
  { id:'card-094', asset:'1 (94).jpg', edges:{north:'field',east:'city',south:'city',west:'city'}, topology:{roads:[],cities:[[1,2,3]],cityShields:[0]}, shields:0 },
  { id:'card-095', asset:'1 (95).jpg', edges:{north:'field',east:'city',south:'city',west:'city'}, topology:{roads:[],cities:[[1,2,3]],cityShields:[0]}, shields:0 },
  { id:'card-096', asset:'1 (96).jpg', edges:{north:'road',east:'field',south:'road',west:'field'}, topology:{roads:[[0,2]],cities:[]}, shields:0 },
  { id:'card-097', asset:'1 (97).jpg', edges:{north:'field',east:'field',south:'road',west:'field'}, topology:{roads:[[2]],cities:[],monastery:true}, shields:0 },
  { id:'card-098', asset:'1 (98).jpg', edges:{north:'city',east:'road',south:'city',west:'road'}, topology:{roads:[[1,3]],cities:[[0,2]],cityShields:[1]}, shields:1 },
  { id:'card-099', asset:'1 (99).jpg', edges:{north:'river',east:'city',south:'city',west:'river'}, topology:{roads:[],cities:[[1,2]],cityShields:[1],riverEdges:[0,3]}, shields:1, riverCard:true, riverKind:'middle' },
  { id:'card-100', asset:'1 (100).jpg', edges:{north:'field',east:'river',south:'river',west:'field'}, topology:{roads:[],cities:[],riverEdges:[1,2]}, shields:0, riverCard:true, riverKind:'middle' },
] as const;

export const AUDITED_CARD_IDS_051_100: readonly string[] = AUDITED_051_100.map((card) => card.id);