/**
 * Card Catalog — Stage 2.5
 *
 * 144 real project card assets (src/game/cards/1 (N).jpg), canonical
 * orientation only (rotation is applied by rotateTile(), never stored here).
 *
 * Data source: pixel classification of the actual images via
 * tools/classify_cards.py. Edge types are filled whenever the edge is
 * visually unambiguous; where internal topology (how road/city ends connect)
 * or special markers could not be determined from the image with confidence,
 * reviewRequired=true is set per stage policy — nothing was guessed.
 *
 * maps.png is a reference asset, NOT a game card, and is intentionally
 * absent from this catalog.
 */

import type { CardDefinition } from './types';

export const CARD_CATALOG: readonly CardDefinition[] = [
  {
    id: 'card-001',
    asset: '1 (1).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-002',
    asset: '1 (2).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-003',
    asset: '1 (3).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-004',
    asset: '1 (4).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-005',
    asset: '1 (5).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-006',
    asset: '1 (6).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-007',
    asset: '1 (7).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-008',
    asset: '1 (8).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-009',
    asset: '1 (9).jpg',
    edges: { north: 'road', east: 'field', south: 'road', west: 'field' },
    topology: { roads: [[2]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-010',
    asset: '1 (10).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'road' },
    topology: { roads: [[2, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-011',
    asset: '1 (11).jpg',
    edges: { north: 'city', east: 'field', south: 'road', west: 'city' },
    topology: { roads: [[2]], cities: [[0], [3]] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'city segmentation unresolved: north and west are both city edges; whether they form ONE continuous city segment around the NW corner or two separate segments cannot be determined because the wall line is broken by a small tower at the corner.',
  },
  {
    id: 'card-012',
    asset: '1 (12).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-013',
    asset: '1 (13).jpg',
    edges: { north: 'city', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [[0]] },
    shields: 0,
  },
  {
    id: 'card-014',
    asset: '1 (14).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-015',
    asset: '1 (15).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-016',
    asset: '1 (16).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-017',
    asset: '1 (17).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-018',
    asset: '1 (18).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-019',
    asset: '1 (19).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-020',
    asset: '1 (20).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-021',
    asset: '1 (21).jpg',
    edges: { north: 'road', east: 'field', south: 'road', west: 'field' },
    topology: { roads: [[2]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-022',
    asset: '1 (22).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-023',
    asset: '1 (23).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'road' },
    topology: { roads: [[2, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-024',
    asset: '1 (24).jpg',
    edges: { north: 'road', east: 'city', south: 'road', west: 'road' },
    topology: { roads: [[0, 2, 3]], cities: [[1]] , monastery: true },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'monastery shield count unresolved: center monastery is confirmed, but the number of shields painted around it (0-3) cannot be read reliably from this scan resolution.',
  },
  {
    id: 'card-025',
    asset: '1 (25).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'road' },
    topology: { roads: [[3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-026',
    asset: '1 (26).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-027',
    asset: '1 (27).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-028',
    asset: '1 (28).jpg',
    edges: { north: 'city', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [[0]] },
    shields: 0,
  },
  {
    id: 'card-029',
    asset: '1 (29).jpg',
    edges: { north: 'field', east: 'field', south: 'city', west: 'city' },
    topology: { roads: [], cities: [[2], [3]] , monastery: true },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'center building identity unresolved: a large structure occupies the tile center inside the S-W city; cannot determine whether it is a city expansion (counts toward city) or a standalone monastery.',
  },
  {
    id: 'card-030',
    asset: '1 (30).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-031',
    asset: '1 (31).jpg',
    edges: { north: 'road', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [[0]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-032',
    asset: '1 (32).jpg',
    edges: { north: 'city', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [[0]] },
    shields: 0,
  },
  {
    id: 'card-033',
    asset: '1 (33).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-034',
    asset: '1 (34).jpg',
    edges: { north: 'road', east: 'field', south: 'road', west: 'field' },
    topology: { roads: [[0, 2]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-035',
    asset: '1 (35).jpg',
    edges: { north: 'city', east: 'road', south: 'road', west: 'road' },
    topology: { roads: [[1, 2, 3]], cities: [[0]] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'road/city junction geometry unresolved: three road edges (E,S,W) each terminate at the boundary of the N city with visible gate openings; whether the roads merge into one shared city feature or touch as separate endpoints changes scoring and needs manual check.',
  },
  {
    id: 'card-036',
    asset: '1 (36).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'field' },
    topology: { roads: [[2]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-037',
    asset: '1 (37).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-038',
    asset: '1 (38).jpg',
    edges: { north: 'city', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [[0]] },
    shields: 0,
  },
  {
    id: 'card-039',
    asset: '1 (39).jpg',
    edges: { north: 'road', east: 'road', south: 'field', west: 'field' },
    topology: { roads: [[0, 1]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-040',
    asset: '1 (40).jpg',
    edges: { north: 'city', east: 'field', south: 'city', west: 'field' },
    topology: { roads: [], cities: [[0], [2]] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'city segmentation unresolved: north and south city edges face each other across the tile; whether one continuous walled city wraps through E/W margins or two separate cities cannot be determined at this scan resolution.',
  },
  {
    id: 'card-041',
    asset: '1 (41).jpg',
    edges: { north: 'city', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [[0]] },
    shields: 0,
  },
  {
    id: 'card-042',
    asset: '1 (42).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'road' },
    topology: { roads: [[3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-043',
    asset: '1 (43).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'EDGE_CLASSIFICATION: all four border strips read as field on this scan, but a road/city feature may exist that does not reach any tile border; center-feature check required.',
  },
  {
    id: 'card-044',
    asset: '1 (44).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-045',
    asset: '1 (45).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-046',
    asset: '1 (46).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'road' },
    topology: { roads: [[2, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-047',
    asset: '1 (47).jpg',
    edges: { north: 'field', east: 'road', south: 'field', west: 'field' },
    topology: { roads: [[1]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-048',
    asset: '1 (48).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'road' },
    topology: { roads: [[2, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-049',
    asset: '1 (49).jpg',
    edges: { north: 'field', east: 'river', south: 'field', west: 'river' },
    topology: { roads: [], cities: [], riverEdges: [1, 3] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-050',
    asset: '1 (50).jpg',
    edges: { north: 'field', east: 'river', south: 'field', west: 'river' },
    topology: { roads: [], cities: [] , monastery: true, riverEdges: [1, 3] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-051',
    asset: '1 (51).jpg',
    edges: { north: 'river', east: 'river', south: 'field', west: 'field' },
    topology: { roads: [], cities: [], riverEdges: [0, 1] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-052',
    asset: '1 (52).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'road' },
    topology: { roads: [[3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-053',
    asset: '1 (53).jpg',
    edges: { north: 'field', east: 'road', south: 'road', west: 'field' },
    topology: { roads: [[1, 2]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-054',
    asset: '1 (54).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-055',
    asset: '1 (55).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-056',
    asset: '1 (56).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-057',
    asset: '1 (57).jpg',
    edges: { north: 'field', east: 'city', south: 'field', west: 'field' },
    topology: { roads: [], cities: [[1]] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'city extent unresolved: an eastern settlement touches the E edge, but whether it wraps around the NE/N corner (making north a second city edge) or stays a single E segment cannot be determined at this scan resolution.',
  },
  {
    id: 'card-058',
    asset: '1 (58).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'field' },
    topology: { roads: [[2]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-059',
    asset: '1 (59).jpg',
    edges: { north: 'road', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [[0]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-060',
    asset: '1 (60).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'EDGE_CLASSIFICATION: all four border strips read as field on this scan, but a road/city feature may exist that does not reach any tile border; center-feature check required.',
  },
  {
    id: 'card-061',
    asset: '1 (61).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-062',
    asset: '1 (62).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-063',
    asset: '1 (63).jpg',
    edges: { north: 'river', east: 'field', south: 'river', west: 'field' },
    topology: { roads: [], cities: [], riverEdges: [0, 2] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-064',
    asset: '1 (64).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-065',
    asset: '1 (65).jpg',
    edges: { north: 'city', east: 'field', south: 'field', west: 'city' },
    topology: { roads: [], cities: [[0], [3]] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'city segmentation unresolved: north and west city edges meet near the NW corner; whether the wall is continuous around the corner (one segment) or split by a road/gate opening needs manual check.',
  },
  {
    id: 'card-066',
    asset: '1 (66).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-067',
    asset: '1 (67).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'field' },
    topology: { roads: [[2]], cities: [] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'EDGE_CLASSIFICATION: a settlement/city cluster is visible just inside the N edge but does not clearly touch the border strip; whether north is city or field requires manual verification.',
  },
  {
    id: 'card-068',
    asset: '1 (68).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-069',
    asset: '1 (69).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-070',
    asset: '1 (70).jpg',
    edges: { north: 'road', east: 'field', south: 'field', west: 'road' },
    topology: { roads: [[0, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-071',
    asset: '1 (71).jpg',
    edges: { north: 'road', east: 'road', south: 'road', west: 'field' },
    topology: { roads: [[0, 1, 2]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-072',
    asset: '1 (72).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'road' },
    topology: { roads: [[3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-073',
    asset: '1 (73).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-074',
    asset: '1 (74).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-075',
    asset: '1 (75).jpg',
    edges: { north: 'river', east: 'field', south: 'river', west: 'field' },
    topology: { roads: [], cities: [], riverEdges: [0, 2] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-076',
    asset: '1 (76).jpg',
    edges: { north: 'road', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [[0]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-077',
    asset: '1 (77).jpg',
    edges: { north: 'road', east: 'road', south: 'road', west: 'road' },
    topology: { roads: [[0, 1, 2, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-078',
    asset: '1 (78).jpg',
    edges: { north: 'road', east: 'road', south: 'road', west: 'road' },
    topology: { roads: [[0, 1, 2, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-079',
    asset: '1 (79).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'field' },
    topology: { roads: [[2]], cities: [] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'EDGE_CLASSIFICATION: a settlement/city cluster is visible just inside the E edge but does not clearly touch the border strip; whether east is city or field requires manual verification.',
  },
  {
    id: 'card-080',
    asset: '1 (80).jpg',
    edges: { north: 'field', east: 'road', south: 'field', west: 'road' },
    topology: { roads: [[1, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-081',
    asset: '1 (81).jpg',
    edges: { north: 'field', east: 'road', south: 'field', west: 'road' },
    topology: { roads: [[1, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-082',
    asset: '1 (82).jpg',
    edges: { north: 'field', east: 'road', south: 'field', west: 'field' },
    topology: { roads: [[1]], cities: [] },
    shields: 0,
    reviewReason: 'road routing ambiguity: road pixels appear at all four edge middle-thirds, but interior rendering shows only two short dead-end stubs (E,S); straight N-S / E-W connections are contradicted by the interior - needs manual verification.'
  },
  {
    id: 'card-083',
    asset: '1 (83).jpg',
    edges: { north: 'road', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [[0]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-084',
    asset: '1 (84).jpg',
    edges: { north: 'river', east: 'field', south: 'field', west: 'river' },
    topology: { roads: [], cities: [], riverEdges: [0, 3] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-085',
    asset: '1 (85).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-086',
    asset: '1 (86).jpg',
    edges: { north: 'river', east: 'field', south: 'field', west: 'river' },
    topology: { roads: [], cities: [], riverEdges: [0, 3] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-087',
    asset: '1 (87).jpg',
    edges: { north: 'field', east: 'river', south: 'river', west: 'field' },
    topology: { roads: [], cities: [], riverEdges: [1, 2] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-088',
    asset: '1 (88).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'road' },
    topology: { roads: [[3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-089',
    asset: '1 (89).jpg',
    edges: { north: 'city', east: 'road', south: 'field', west: 'field' },
    topology: { roads: [[1]], cities: [[0]] },
    shields: 0,
  },
  {
    id: 'card-090',
    asset: '1 (90).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'field' },
    topology: { roads: [[2]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-091',
    asset: '1 (91).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-092',
    asset: '1 (92).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] , monastery: true },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'possible center building detected: gray structure at tile center; cannot confirm monastery vs field decoration at this scan resolution.',
  },
  {
    id: 'card-093',
    asset: '1 (93).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-094',
    asset: '1 (94).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'field' },
    topology: { roads: [[2]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-095',
    asset: '1 (95).jpg',
    edges: { north: 'river', east: 'field', south: 'field', west: 'river' },
    topology: { roads: [], cities: [], riverEdges: [0, 3] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-096',
    asset: '1 (96).jpg',
    edges: { north: 'field', east: 'river', south: 'river', west: 'field' },
    topology: { roads: [], cities: [], riverEdges: [1, 2] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-097',
    asset: '1 (97).jpg',
    edges: { north: 'field', east: 'river', south: 'field', west: 'river' },
    topology: { roads: [], cities: [], riverEdges: [1, 3] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-098',
    asset: '1 (98).jpg',
    edges: { north: 'field', east: 'river', south: 'river', west: 'field' },
    topology: { roads: [], cities: [], riverEdges: [1, 2] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-099',
    asset: '1 (99).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-100',
    asset: '1 (100).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-101',
    asset: '1 (101).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-102',
    asset: '1 (102).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'river' },
    topology: { roads: [], cities: [], riverEdges: [3] },
    shields: 0,
    riverCard: true,
    riverKind: 'end',
  },
  {
    id: 'card-103',
    asset: '1 (103).jpg',
    edges: { north: 'field', east: 'river', south: 'field', west: 'river' },
    topology: { roads: [], cities: [], riverEdges: [1, 3] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-104',
    asset: '1 (104).jpg',
    edges: { north: 'field', east: 'river', south: 'field', west: 'river' },
    topology: { roads: [], cities: [], riverEdges: [1, 3] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-105',
    asset: '1 (105).jpg',
    edges: { north: 'river', east: 'river', south: 'field', west: 'river' },
    topology: { roads: [], cities: [] , monastery: true, riverEdges: [0, 1, 3] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-106',
    asset: '1 (106).jpg',
    edges: { north: 'field', east: 'river', south: 'field', west: 'river' },
    topology: { roads: [], cities: [] , monastery: true, riverEdges: [1, 3] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-107',
    asset: '1 (107).jpg',
    edges: { north: 'field', east: 'river', south: 'river', west: 'field' },
    topology: { roads: [], cities: [], riverEdges: [1, 2] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-108',
    asset: '1 (108).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'city' },
    topology: { roads: [], cities: [[3]] },
    shields: 0,
  },
  {
    id: 'card-109',
    asset: '1 (109).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'city' },
    topology: { roads: [], cities: [[3]] },
    shields: 0,
  },
  {
    id: 'card-110',
    asset: '1 (110).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-111',
    asset: '1 (111).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-112',
    asset: '1 (112).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-113',
    asset: '1 (113).jpg',
    edges: { north: 'field', east: 'city', south: 'field', west: 'field' },
    topology: { roads: [], cities: [[1]] },
    shields: 0,
  },
  {
    id: 'card-114',
    asset: '1 (114).jpg',
    edges: { north: 'field', east: 'city', south: 'field', west: 'city' },
    topology: { roads: [], cities: [[1, 3]] },
    shields: 0,
  },
  {
    id: 'card-115',
    asset: '1 (115).jpg',
    edges: { north: 'road', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [[0]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-116',
    asset: '1 (116).jpg',
    edges: { north: 'field', east: 'road', south: 'field', west: 'road' },
    topology: { roads: [[1, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-117',
    asset: '1 (117).jpg',
    edges: { north: 'river', east: 'field', south: 'river', west: 'field' },
    topology: { roads: [], cities: [], riverEdges: [0, 2] },
    shields: 0,
    riverCard: true,
    riverKind: 'middle',
  },
  {
    id: 'card-118',
    asset: '1 (118).jpg',
    edges: { north: 'road', east: 'road', south: 'field', west: 'field' },
    topology: { roads: [[0, 1]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-119',
    asset: '1 (119).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-120',
    asset: '1 (120).jpg',
    edges: { north: 'field', east: 'city', south: 'field', west: 'field' },
    topology: { roads: [], cities: [[1]] },
    shields: 0,
  },
  {
    id: 'card-121',
    asset: '1 (121).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-122',
    asset: '1 (122).jpg',
    edges: { north: 'field', east: 'field', south: 'road', west: 'road' },
    topology: { roads: [[2, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-123',
    asset: '1 (123).jpg',
    edges: { north: 'field', east: 'city', south: 'field', west: 'field' },
    topology: { roads: [], cities: [[1]] },
    shields: 0,
  },
  {
    id: 'card-124',
    asset: '1 (124).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-125',
    asset: '1 (125).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-126',
    asset: '1 (126).jpg',
    edges: { north: 'field', east: 'city', south: 'field', west: 'city' },
    topology: { roads: [], cities: [[1], [3]] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'city segmentation unresolved: east and west city edges both show city walls; whether they belong to one city wrapping through N/S margins or two separate cities cannot be determined.',
  },
  {
    id: 'card-127',
    asset: '1 (127).jpg',
    edges: { north: 'field', east: 'field', south: 'city', west: 'field' },
    topology: { roads: [], cities: [[2]] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'city extent unresolved: S city wall extends toward the E edge margin; whether the city segment includes the east edge (two-edge group) or stays a single S segment needs manual check.',
  },
  {
    id: 'card-128',
    asset: '1 (128).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-129',
    asset: '1 (129).jpg',
    edges: { north: 'field', east: 'field', south: 'river', west: 'field' },
    topology: { roads: [], cities: [], monastery: true, riverEdges: [2] },
    shields: 0,
    riverCard: true,
    riverKind: 'start',
    reviewRequired: true,
    reviewReason: 'monastery shield count unresolved: river source side (S) and monastery presence are confirmed; the number of shields around the monastery (0-3) cannot be read reliably from this scan.',
  },
  {
    id: 'card-130',
    asset: '1 (130).jpg',
    edges: { north: 'road', east: 'field', south: 'road', west: 'field' },
    topology: { roads: [[0, 2]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-131',
    asset: '1 (131).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-132',
    asset: '1 (132).jpg',
    edges: { north: 'field', east: 'city', south: 'field', west: 'field' },
    topology: { roads: [], cities: [[1]] },
    shields: 0,
  },
  {
    id: 'card-133',
    asset: '1 (133).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-134',
    asset: '1 (134).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-135',
    asset: '1 (135).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-136',
    asset: '1 (136).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-137',
    asset: '1 (137).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-138',
    asset: '1 (138).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
  {
    id: 'card-139',
    asset: '1 (139).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'city' },
    topology: { roads: [], cities: [[3]] },
    shields: 0,
  },
  {
    id: 'card-140',
    asset: '1 (140).jpg',
    edges: { north: 'road', east: 'road', south: 'field', west: 'road' },
    topology: { roads: [[0, 1, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-141',
    asset: '1 (141).jpg',
    edges: { north: 'road', east: 'road', south: 'field', west: 'field' },
    topology: { roads: [[0, 1]], cities: [] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'NE-village/N-edge road topology requires manual verification',
  },
  {
    id: 'card-142',
    asset: '1 (142).jpg',
    edges: { north: 'road', east: 'field', south: 'field', west: 'road' },
    topology: { roads: [[0, 3]], cities: [] },
    shields: 0,
  },
  {
    id: 'card-143',
    asset: '1 (143).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
    reviewRequired: true,
    reviewReason: 'EDGE_CLASSIFICATION: all four border strips read as field on this scan, but a road/city feature may exist that does not reach any tile border; center-feature check required.',
  },
  {
    id: 'card-144',
    asset: '1 (144).jpg',
    edges: { north: 'field', east: 'field', south: 'field', west: 'field' },
    topology: { roads: [], cities: [] },
    shields: 0,
  },
];

/** Reference image only — not a game card, never enters the deck. */
export const MAPS_ASSET_NAME = 'maps.png';

export function getCardById(id: string): CardDefinition | undefined {
  return CARD_CATALOG.find((c) => c.id === id);
}

export function getReviewRequiredCards(): CardDefinition[] {
  return CARD_CATALOG.filter((c) => c.reviewRequired);
}
