export type GameSound='click'|'preview'|'rotate'|'tile'|'meeple'|'turn'|'score'|'warning'|'finished';
export interface AudioPreferences {soundEnabled:boolean;musicEnabled:boolean}
let preferences:AudioPreferences={soundEnabled:true,musicEnabled:true},context:AudioContext|null=null,unlocked=false,music:OscillatorNode[]=[];
const tones:Record<GameSound,[number,number,number]>={click:[320,0.025,.018],preview:[440,.045,.025],rotate:[520,.04,.02],tile:[220,.1,.04],meeple:[620,.09,.03],turn:[392,.13,.025],score:[784,.16,.035],warning:[250,.12,.025],finished:[523,.3,.04]};
function audioContext():AudioContext|null{try{const Constructor=window.AudioContext??(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;return Constructor?(context??=new Constructor()):null;}catch{return null;}}
function stopMusic(){for(const node of music){try{node.stop();}catch{/* already stopped */}}music=[];}
function syncMusic(){stopMusic();if(!unlocked||!preferences.musicEnabled)return;const ctx=audioContext();if(!ctx)return;const gain=ctx.createGain();gain.gain.value=.012;gain.connect(ctx.destination);for(const [frequency,detune] of [[110,-5],[165,5]] as const){const oscillator=ctx.createOscillator();oscillator.type='sine';oscillator.frequency.value=frequency;oscillator.detune.value=detune;oscillator.connect(gain);oscillator.start();music.push(oscillator);}}
export function configureAudio(next:AudioPreferences):void{const musicChanged=next.musicEnabled!==preferences.musicEnabled;preferences=next;if(musicChanged)syncMusic();}
export async function unlockAudio():Promise<void>{if(unlocked)return;const ctx=audioContext();if(!ctx)return;try{await ctx.resume();unlocked=true;syncMusic();}catch{/* Audio is enhancement-only. */}}
export function playGameSound(sound:GameSound):void{if(!unlocked||!preferences.soundEnabled)return;const ctx=audioContext();if(!ctx)return;try{const [frequency,duration,volume]=tones[sound],oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.frequency.value=frequency;oscillator.type=sound==='tile'?'triangle':'sine';gain.gain.setValueAtTime(volume,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+duration);oscillator.connect(gain).connect(ctx.destination);oscillator.start();oscillator.stop(ctx.currentTime+duration);}catch{/* Never interrupt gameplay. */}}
export function installAudioGestureUnlock():()=>void{const unlock=()=>{void unlockAudio();};const click=(event:Event)=>{if((event.target as Element|null)?.closest('button'))playGameSound('click');};window.addEventListener('pointerdown',unlock,{once:true,capture:true});window.addEventListener('keydown',unlock,{once:true,capture:true});document.addEventListener('click',click);return()=>{window.removeEventListener('pointerdown',unlock,{capture:true});window.removeEventListener('keydown',unlock,{capture:true});document.removeEventListener('click',click);};}
export function audioRuntimeState(){return{contextCreated:context!==null,unlocked,musicNodes:music.length};}
