import { ensureOnlineIdentity } from './auth';
import { requireSupabaseClient } from './supabaseClient';
import type { OnlineMatch, OnlineMatchActionRequest, OnlineMatchActionResponse, OnlinePublicMatchSnapshot } from './matchTypes';

type MatchRow = { id:string; lobby_id:string; version:number; status:OnlineMatch['status']; current_player_id:string|null; turn_number:number; snapshot:OnlinePublicMatchSnapshot; created_at:string; updated_at:string };
const fromRow=(row:MatchRow):OnlineMatch=>({id:row.id,lobbyId:row.lobby_id,version:row.version,status:row.status,currentPlayerId:row.current_player_id,turnNumber:row.turn_number,snapshot:row.snapshot,createdAt:row.created_at,updatedAt:row.updated_at});
async function accessToken():Promise<string>{await ensureOnlineIdentity();const {data,error}=await requireSupabaseClient().auth.getSession();if(error)throw error;if(!data.session?.access_token)throw new Error('Authenticated online session is unavailable.');return data.session.access_token;}
async function post<T>(path:string,body:unknown):Promise<T>{const token=await accessToken();const response=await fetch(path,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify(body)});const payload=await response.json() as {code?:string;message?:string};if(!response.ok)throw Object.assign(new Error(payload.message??'Online match request failed.'),{code:payload.code,status:response.status});return payload as T;}
export const startOnlineMatch=(lobbyId:string)=>post<OnlineMatch>('/api/online/match/start',{lobbyId});
export const submitMatchIntent=(request:OnlineMatchActionRequest)=>post<OnlineMatchActionResponse>('/api/online/match/action',request);
export async function getMatch(matchId:string):Promise<OnlineMatch>{await ensureOnlineIdentity();const {data,error}=await requireSupabaseClient().from('online_matches').select('*').eq('id',matchId).single();if(error)throw error;return fromRow(data as MatchRow);}
export async function getMatchByLobby(lobbyId:string):Promise<OnlineMatch>{await ensureOnlineIdentity();const {data,error}=await requireSupabaseClient().from('online_matches').select('*').eq('lobby_id',lobbyId).single();if(error)throw error;return fromRow(data as MatchRow);}
export function subscribeToMatch(matchId:string,callback:(match:OnlineMatch|null,error?:Error)=>void):()=>void{const client=requireSupabaseClient();let running=false,pending=false;const refresh=()=>{if(running){pending=true;return;}running=true;void getMatch(matchId).then(callback).catch((e:unknown)=>callback(null,e instanceof Error?e:new Error(String(e)))).finally(()=>{running=false;if(pending){pending=false;refresh();}})};const channel=client.channel(`online-match:${matchId}`).on('postgres_changes',{event:'*',schema:'public',table:'online_matches',filter:`id=eq.${matchId}`},refresh).subscribe(status=>{if(status==='SUBSCRIBED')refresh();});return()=>{void client.removeChannel(channel)};}
