import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import startHandler from '../../../api/online/match/start';
import actionHandler from '../../../api/online/match/action';
import { advanceToPlayableDraw,applyOnlineMatchIntent,assertActorTurn,buildEnginePlayers,buildPublicMatchSnapshot,createTurnFlow } from '../../../api/_lib/matchCore';
import { confirmTurnTilePlacement,placeTurnTile,rotatePositionedTurnTile } from '../../game/engine/turnFlow';
import type { OnlineMatchIntent } from '../matchTypes';

const players=[{id:'10000000-0000-4000-8000-000000000001',name:'A',color:'blue',score:0},{id:'10000000-0000-4000-8000-000000000002',name:'B',color:'red',score:0}];
function response(){let status=0;let body:unknown;const value={status(code:number){status=code;return value;},json(payload:unknown){body=payload;}};return {value,get:()=>({status,body})};}

describe('Stage 5D.1 authoritative match core',()=>{
 it('auto draws through the existing river flow and public snapshot hides future state',()=>{const flow=advanceToPlayableDraw(createTurnFlow({gameId:'match',players,seed:42}));expect(flow.phase).toBe('TILE_IN_HAND');expect(flow.game.drawnTileDefinitionId).toBeTruthy();expect(flow.riverPlaced).toBe(1);expect(flow.game.board['0,0'].definitionId).toBe('card-133');const future=[...flow.riverDeck,...flow.landDeck];const snapshot=buildPublicMatchSnapshot(flow);const json=JSON.stringify(snapshot);for(const key of ['riverDeck','landDeck','seed','tileDeck','discardedTileIds'])expect(json).not.toContain(`"${key}"`);expect(future.some(id=>json.includes(`"${id}"`))).toBe(false);expect(snapshot.game.board).toBeTruthy();expect(snapshot.game.players).toHaveLength(2);expect(snapshot.derived.legalTilePlacementOptions.length).toBeGreaterThan(0);});
 it('PLACE_TILE delegates exact rotation to TurnFlow helpers',()=>{const flow=advanceToPlayableDraw(createTurnFlow({gameId:'match',players,seed:7}));const option=buildPublicMatchSnapshot(flow).derived.legalTilePlacementOptions[0];expect(option).toBeTruthy();const rotation=option.rotations[option.rotations.length-1];const intent:OnlineMatchIntent={type:'PLACE_TILE',position:option.position,rotation};const adapted=applyOnlineMatchIntent(flow,intent);let direct=placeTurnTile(flow,option.position);for(let i=0;direct.rotation!==rotation&&i<4;i++)direct=rotatePositionedTurnTile(direct);direct=confirmTurnTilePlacement(direct);expect(adapted).toEqual(direct);expect(adapted.phase).toBe('TILE_PLACED');});
 it('rejects illegal placement and wrong phase without inventing rules',()=>{const flow=advanceToPlayableDraw(createTurnFlow({gameId:'match',players,seed:9}));expect(()=>applyOnlineMatchIntent(flow,{type:'PLACE_TILE',position:{x:999,y:999},rotation:0})).toThrow('illegal');expect(()=>applyOnlineMatchIntent(flow,{type:'END_TURN'})).toThrow('cannot end');});
 it('END_TURN scores through the engine and auto draws once',()=>{let flow=advanceToPlayableDraw(createTurnFlow({gameId:'match',players,seed:11}));const option=buildPublicMatchSnapshot(flow).derived.legalTilePlacementOptions[0];flow=applyOnlineMatchIntent(flow,{type:'PLACE_TILE',position:option.position,rotation:option.rotations[0]});const turn=flow.game.turnNumber;const next=applyOnlineMatchIntent(flow,{type:'END_TURN'});expect(next.game.turnNumber).toBe(turn+1);expect(['TILE_IN_HAND','GAME_OVER']).toContain(next.phase);});
 it('creates deterministic human and bot roster identities by seat',()=>{const result=buildEnginePlayers('m',[{seatIndex:0,userId:'u',displayName:'Human'}],4,3);expect(result.players.map(p=>p.id)).toEqual(['u','bot:m:1','bot:m:2','bot:m:3']);expect(result.players.map(p=>p.color)).toEqual(['blue','red','green','yellow']);});
 it('rejects non-members, wrong actors, and humans acting for bots',()=>{const flow=advanceToPlayableDraw(createTurnFlow({gameId:'match',players,seed:42}));const roster=players.map(p=>({playerId:p.id,userId:p.id,isBot:false}));expect(()=>assertActorTurn(flow,'outsider',roster)).toThrow('not a match participant');expect(()=>assertActorTurn(flow,players[1].id,roster)).toThrow('another player');const botFlow={...flow,game:{...flow.game,players:[{...flow.game.players[0],id:'bot:match:0'}]}};expect(()=>assertActorTurn(botFlow,players[1].id,[{playerId:'bot:match:0',userId:null,isBot:true},{playerId:players[1].id,userId:players[1].id,isBot:false}])).toThrow('bot turn');});
 it.each([{handler:startHandler,name:'start'},{handler:actionHandler,name:'action'}])('$name endpoint rejects missing authorization without leaking details',async({handler})=>{const out=response();await handler({method:'POST',headers:{},body:{}},out.value);expect(out.get().status).toBe(401);expect(out.get().body).toEqual({code:'UNAUTHORIZED',message:'Authorization required.'});});
 it('migration creates protected state, atomic service RPCs, and public-only realtime',()=>{const sql=readFileSync(join(process.cwd(),'supabase/migrations/20261002062013_stage5d1_authoritative_match_core.sql'),'utf8');for(const table of ['online_matches','online_match_players','online_match_states','online_match_actions'])expect(sql).toContain(`create table public.${table}`);expect(sql).toContain('where id=p_match_id for update');expect(sql).toContain("raise exception 'VERSION_CONFLICT'");expect(sql).toContain("jsonb_build_object('idempotent',true");expect(sql).toContain('to service_role');expect(sql).toContain('alter publication supabase_realtime add table public.online_matches');expect(sql).not.toMatch(/alter publication supabase_realtime add table public\.online_match_(states|actions)/);});
 it('client source never imports server admin and env naming never exposes service role to Vite',()=>{const source=readFileSync(join(process.cwd(),'src/online/matchApi.ts'),'utf8');expect(source).not.toContain('supabaseAdmin');expect(readFileSync(join(process.cwd(),'.env.example'),'utf8')).not.toContain('VITE_SUPABASE_SERVICE_ROLE_KEY');});
});
