import { authenticateBearer,getSupabaseAdmin } from '../../_lib/supabaseAdmin';
import { type ApiRequest,type ApiResponse,requirePost,sendError } from '../../_lib/http';
import { applyOnlineMatchIntent,assertActorTurn,buildPublicMatchSnapshot,MatchIntentError } from '../../_lib/matchCore';
import type { TurnFlowState } from '../../../src/game/engine/turnFlow';
import type { OnlineMatchActionRequest,OnlineMatchIntent } from '../../../src/online/matchTypes';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function validIntent(value:unknown):value is OnlineMatchIntent{if(!value||typeof value!=='object')return false;const i=value as Record<string,unknown>;if(i.type==='END_TURN')return true;if(i.type==='PLACE_TILE'){const p=i.position as Record<string,unknown>|null;return !!p&&Number.isInteger(p.x)&&Number.isInteger(p.y)&&[0,90,180,270].includes(i.rotation as number);}if(i.type==='PLACE_MEEPLE')return ['road','city','monastery'].includes(String(i.featureType))&&(i.edge===null||[0,1,2,3].includes(i.edge as number));return false;}
function validBody(value:unknown):value is OnlineMatchActionRequest{if(!value||typeof value!=='object')return false;const b=value as Record<string,unknown>;return typeof b.matchId==='string'&&uuid.test(b.matchId)&&Number.isSafeInteger(b.expectedVersion)&&(b.expectedVersion as number)>=0&&typeof b.intentId==='string'&&uuid.test(b.intentId)&&validIntent(b.intent);}
export default async function handler(request:ApiRequest,response:ApiResponse):Promise<void>{try{requirePost(request);const actor=await authenticateBearer(typeof request.headers.authorization==='string'?request.headers.authorization:undefined);if(!validBody(request.body))throw Object.assign(new Error('Invalid request body.'),{status:400,code:'INVALID_BODY'});const body=request.body;const admin=getSupabaseAdmin();const roster=await admin.from('online_match_players').select('player_id,user_id,is_bot').eq('match_id',body.matchId);if(roster.error)throw roster.error;const member=roster.data.find(p=>p.user_id===actor&&!p.is_bot);if(!member)throw Object.assign(new Error('Actor is not a match participant.'),{status:403,code:'FORBIDDEN'});const duplicate=await admin.from('online_match_actions').select('id').eq('match_id',body.matchId).eq('intent_id',body.intentId).maybeSingle();if(duplicate.data){const accepted=await admin.from('online_matches').select('*').eq('id',body.matchId).single();if(accepted.error)throw accepted.error;response.status(200).json({match:accepted.data,idempotent:true});return;}
 const matchResult=await admin.from('online_matches').select('id,version,status,current_player_id,turn_deadline_at').eq('id',body.matchId).single();if(matchResult.error)throw Object.assign(new Error('Match not found.'),{status:404,code:'NOT_FOUND'});const match=matchResult.data;if(match.status!=='playing')throw new MatchIntentError('MATCH_FINISHED','Match does not accept actions.');if(match.version!==body.expectedVersion)throw new MatchIntentError('VERSION_CONFLICT','Match version is stale.');if(match.turn_deadline_at&&Date.now()>=Date.parse(match.turn_deadline_at))throw new MatchIntentError('TURN_EXPIRED','The turn deadline has passed.');
 const stateResult=await admin.from('online_match_states').select('state').eq('match_id',body.matchId).single();if(stateResult.error)throw stateResult.error;const state=stateResult.data.state as TurnFlowState;assertActorTurn(state,actor,roster.data.map(p=>({playerId:p.player_id,userId:p.user_id,isBot:p.is_bot})));const next=applyOnlineMatchIntent(state,body.intent);const snapshot=buildPublicMatchSnapshot(next);const status=next.phase==='GAME_OVER'?'finished':'playing';const currentPlayerId=next.game.players[next.game.currentPlayerIndex]?.id??null;const committed=await admin.rpc('commit_online_match_transition_server',{p_match_id:body.matchId,p_expected_version:body.expectedVersion,p_intent_id:body.intentId,p_actor_user_id:actor,p_action_type:body.intent.type,p_payload:body.intent,p_state:next,p_snapshot:snapshot,p_current_player_id:currentPlayerId,p_turn_number:next.game.turnNumber,p_status:status,p_source:'human',p_turn_advanced:body.intent.type==='END_TURN'});if(committed.error){const message=committed.error.message;if(message.includes('VERSION_CONFLICT'))throw new MatchIntentError('VERSION_CONFLICT','Match version is stale.');if(message.includes('TURN_EXPIRED'))throw new MatchIntentError('TURN_EXPIRED','The turn deadline has passed.');throw committed.error;}const result=committed.data as {idempotent:boolean};const refreshed=await admin.from('online_matches').select('*').eq('id',body.matchId).single();if(refreshed.error)throw refreshed.error;response.status(200).json({match:refreshed.data,idempotent:result.idempotent});
 }catch(error){sendError(response,error);}}
