import { randomBytes, randomUUID } from 'node:crypto';
import { authenticateBearer, getSupabaseAdmin } from '../../_lib/supabaseAdmin';
import { type ApiRequest,type ApiResponse,requirePost,sendError } from '../../_lib/http';
import { advanceToPlayableDraw,buildEnginePlayers,buildPublicMatchSnapshot,createTurnFlow } from '../../_lib/matchCore';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export default async function handler(request:ApiRequest,response:ApiResponse):Promise<void>{try{requirePost(request);const actor=await authenticateBearer(typeof request.headers.authorization==='string'?request.headers.authorization:undefined);const body=request.body as Record<string,unknown>|null;if(!body||typeof body.lobbyId!=='string'||!uuid.test(body.lobbyId))throw Object.assign(new Error('Invalid request body.'),{status:400,code:'INVALID_BODY'});const admin=getSupabaseAdmin();
 const {data:lobby,error}=await admin.from('online_lobbies').select('id,host_user_id,status,max_players,bot_slots,turn_timer_seconds,online_lobby_players(user_id,seat_index,display_name)').eq('id',body.lobbyId).single();if(error||!lobby)throw Object.assign(new Error('Lobby not found.'),{status:404,code:'NOT_FOUND'});if(lobby.host_user_id!==actor)throw Object.assign(new Error('Only the lobby host can start a match.'),{status:403,code:'FORBIDDEN'});
 const existing=await admin.from('online_matches').select('*').eq('lobby_id',body.lobbyId).maybeSingle();if(existing.data){response.status(200).json(existing.data);return;}if(lobby.status!=='starting')throw Object.assign(new Error('Lobby is not starting.'),{status:409,code:'LOBBY_NOT_STARTING'});
 const matchId=randomUUID();const humanRows=(lobby.online_lobby_players as Array<{user_id:string;seat_index:number;display_name:string}>).map(p=>({seatIndex:p.seat_index,userId:p.user_id,displayName:p.display_name}));const {players,roster}=buildEnginePlayers(matchId,humanRows,lobby.max_players,lobby.bot_slots);const seed=randomBytes(4).readUInt32LE(0);const flow=advanceToPlayableDraw(createTurnFlow({gameId:matchId,players,seed}));const snapshot=buildPublicMatchSnapshot(flow);const rosterPayload=roster.map(r=>({seat_index:r.seatIndex,player_id:r.userId??`bot:${matchId}:${r.seatIndex}`,user_id:r.userId,display_name:r.displayName,is_bot:r.isBot,color:players.find(p=>p.id===(r.userId??`bot:${matchId}:${r.seatIndex}`))?.color??'black'}));const currentPlayerId=flow.game.players[flow.game.currentPlayerIndex]?.id??null;
 const {data,error:rpcError}=await admin.rpc('create_online_match_server',{p_lobby_id:body.lobbyId,p_actor_user_id:actor,p_match_id:matchId,p_state:flow,p_snapshot:snapshot,p_players:rosterPayload,p_current_player_id:currentPlayerId,p_turn_number:flow.game.turnNumber,p_status:flow.phase==='GAME_OVER'?'finished':'playing',p_turn_timer_seconds:lobby.turn_timer_seconds});if(rpcError)throw rpcError;const result=await admin.from('online_matches').select('*').eq('id',String(data)).single();if(result.error)throw result.error;response.status(200).json(result.data);
 }catch(error){sendError(response,error);}}
