import { useCallback,useEffect,useLayoutEffect,useMemo,useRef,useState } from 'react';
import { getTileDefinition } from '../../game/cards/catalogApi';
import type { MeeplePlacement } from '../../game/types/geometry';
import { anchorForPlacement } from '../tiles/tileSemanticManifest';
import { TileRenderer } from '../tiles/TileRenderer';
import { useBoardCamera } from '../game/useBoardCamera';
import { ensureOnlineIdentity } from '../../online/auth';
import { getMatch,pumpMatch,submitMatchIntent,subscribeToMatch,type MatchConnectionStatus } from '../../online/matchApi';
import type { OnlineMatch,OnlineMatchIntent } from '../../online/matchTypes';
import { attemptAfterMeepleDraftChange,attemptAfterTileDraftChange,availableMeeples,currentPlayerId,EMPTY_ONLINE_DRAFTS,LogicalIntentAttempt,reconcileMatch,rotateTileDraft,selectTileDraft,shouldPromptSkipMeeple,tileIntent,type OnlineDraftState } from './onlineGameModel';
import { OnlineMatchChat } from './OnlineMatchChat';
import { onlineHandVisible } from '../game/draftVisibility';
import { OnlineTurnHud } from '../game/OnlineTurnHud';
import { scoreDeltas } from '../game/gamePresentationModel';
import { GameIcon } from '../icons/GameIcon';
import { playGameSound } from '../../audio/gameAudio';
import { clearActiveMatch } from '../../online/activeMatchPersistence';
import { MeepleSprite } from './MeepleSprite';
import './onlineGame.css';
import './onlineGamePolishV2.css';
import './onlineGamePolishV3.css';
import './onlineGamePolishV4.css';

const CELL=86,PADDING=2,TOTAL_TILE_COUNT=143;
const targetKey=(target:MeeplePlacement)=>`${target.featureType}:${target.edge??'center'}`;
const featureLabel=(target:MeeplePlacement)=>target.featureType==='city'?'город':target.featureType==='road'?'дорогу':'монастырь';
const SimpleChatGlyph=()=> <svg className="simple-chat-glyph" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 5h16v11H9l-5 4V5Z"/></svg>;

export function OnlineGamePage({initialMatch,onExit}:{initialMatch:OnlineMatch;onExit:()=>void}){
 const [match,setMatch]=useState(initialMatch),[userId,setUserId]=useState(''),[drafts,setDrafts]=useState<OnlineDraftState>(EMPTY_ONLINE_DRAFTS),[attempt,setAttempt]=useState<LogicalIntentAttempt|null>(null),[pending,setPending]=useState(false),[feedback,setFeedback]=useState(''),[skipConfirm,setSkipConfirm]=useState(false),[chatOpen,setChatOpen]=useState(false),[playersExpanded,setPlayersExpanded]=useState(false),[connection,setConnection]=useState<MatchConnectionStatus>('reconnecting'),[deltas,setDeltas]=useState<Record<string,number>>({}),[turnNotice,setTurnNotice]=useState('');
 const pendingRef=useRef(false),draftsRef=useRef(drafts),pumped=useRef(new Set<string>()),previousScores=useRef(initialMatch.snapshot.game.scores),previousPlayer=useRef(initialMatch.currentPlayerId),viewportRef=useRef<HTMLDivElement>(null);draftsRef.current=drafts;
 const acceptAuthoritative=useCallback((incoming:OnlineMatch)=>{setMatch(current=>{const next=reconcileMatch(current,incoming,draftsRef.current);if(next.changed){setDrafts(next.drafts);setAttempt(null);setSkipConfirm(false);setFeedback('');}return next.match;});},[]);
 const refetch=useCallback(async()=>{try{acceptAuthoritative(await getMatch(match.id));setConnection('connected');}catch{setConnection('offline');setFeedback('Нет связи с сервером');}},[acceptAuthoritative,match.id]);
 useEffect(()=>{void ensureOnlineIdentity().then(setUserId).catch(()=>setFeedback('Не удалось подключиться к сетевой игре'));return subscribeToMatch(match.id,(incoming,error)=>{if(error){setFeedback('Нет связи с сервером');return;}if(incoming)acceptAuthoritative(incoming);},setConnection);},[acceptAuthoritative,match.id]);
 useEffect(()=>{const online=()=>{setConnection('reconnecting');void refetch();},offline=()=>{setConnection('offline');setFeedback('Нет связи с сервером');},visible=()=>{if(document.visibilityState==='visible'){setConnection('reconnecting');void refetch();}};window.addEventListener('online',online);window.addEventListener('offline',offline);document.addEventListener('visibilitychange',visible);return()=>{window.removeEventListener('online',online);window.removeEventListener('offline',offline);document.removeEventListener('visibilitychange',visible);};},[refetch]);
 const snapshot=match.snapshot,activeId=currentPlayerId(match),botTurn=activeId?.startsWith('bot:')??false,myTurn=activeId===userId,statusFinished=match.status==='finished'||snapshot.flow.phase==='GAME_OVER';
 const available=availableMeeples(match,userId);
 const rankedPlayers=useMemo(()=>snapshot.game.players.map((player,index)=>({player,index,score:snapshot.game.scores[player.id]??player.score??0})).sort((a,b)=>b.score-a.score||a.index-b.index),[snapshot.game.players,snapshot.game.scores]);
 const visiblePlayers=rankedPlayers.slice(0,2);
 const boardTiles=useMemo(()=>Object.values(snapshot.game.board),[snapshot.game.board]);
 const remainingTiles=snapshot.flow.remainingTileCount??Math.max(0,TOTAL_TILE_COUNT-boardTiles.length-(snapshot.game.drawnTileDefinitionId?1:0));
 const currentPlayerColor=snapshot.game.players[snapshot.game.currentPlayerIndex]?.color??'blue';
 const myColor=snapshot.game.players.find(player=>player.id===userId)?.color??currentPlayerColor;
 const positions=useMemo(()=>{const result=boardTiles.map(t=>t.position);if(myTurn&&snapshot.flow.phase==='TILE_IN_HAND')result.push(...snapshot.derived.legalTilePlacementOptions.map(o=>o.position));if(drafts.tileDraft)result.push(drafts.tileDraft.position);return result.length?result:[{x:0,y:0}];},[boardTiles,myTurn,snapshot.flow.phase,snapshot.derived.legalTilePlacementOptions,drafts.tileDraft]);
 const projection=useMemo(()=>{const minX=Math.min(...positions.map(p=>p.x))-PADDING,minY=Math.min(...positions.map(p=>p.y))-PADDING,maxX=Math.max(...positions.map(p=>p.x))+PADDING,maxY=Math.max(...positions.map(p=>p.y))+PADDING;return {originX:-minX,originY:-minY,width:(maxX-minX+1)*CELL,height:(maxY-minY+1)*CELL};},[positions]);
 const fitCells=useCallback(()=>positions,[positions]);
 const camera=useBoardCamera({viewportRef,contentWidth:projection.width,contentHeight:projection.height,getFitCells:fitCells,cellSize:CELL,originOffset:{x:projection.originX,y:projection.originY}});
 const fitDone=useRef(false);useLayoutEffect(()=>{if(!fitDone.current){fitDone.current=true;camera.fitContent();}},[camera.fitContent]);
 const requestPump=useCallback(()=>{const key=`${match.version}:${match.turnDeadlineAt??'bot'}`;if(pumped.current.has(key)||statusFinished)return;pumped.current.add(key);void pumpMatch(match.id).then(result=>{if(result.processed)void getMatch(match.id).then(setMatch);}).catch(()=>setFeedback('Автоматизация временно недоступна.'));},[match.id,match.turnDeadlineAt,match.version,statusFinished]);
 useEffect(()=>{if(botTurn)requestPump();},[botTurn,requestPump]);
 useEffect(()=>{const next=scoreDeltas(previousScores.current,snapshot.game.scores);previousScores.current=snapshot.game.scores;if(Object.keys(next).length){playGameSound('score');setDeltas(next);const timer=setTimeout(()=>setDeltas({}),900);return()=>clearTimeout(timer);}},[snapshot.game.scores]);
 useEffect(()=>{if(previousPlayer.current===activeId)return;previousPlayer.current=activeId??null;playGameSound('turn');const name=snapshot.game.players.find(p=>p.id===activeId)?.name??'—';setTurnNotice(myTurn?'Ваш ход':botTurn?'Бот думает…':`Ход: ${name}`);const timer=setTimeout(()=>setTurnNotice(''),1200);return()=>clearTimeout(timer);},[activeId,botTurn,myTurn,snapshot.game.players]);
 useEffect(()=>{if(statusFinished)playGameSound('finished');},[statusFinished]);
 useEffect(()=>{if(match.status==='finished'||match.status==='abandoned')clearActiveMatch();},[match.status]);
 const applyMatch=(incoming:OnlineMatch)=>{setMatch(current=>incoming.version>=current.version?incoming:current);setDrafts(EMPTY_ONLINE_DRAFTS);setAttempt(null);};
 const send=async(intent:OnlineMatchIntent)=>{if(pendingRef.current)return;const logical=attempt??new LogicalIntentAttempt(intent,()=>crypto.randomUUID());if(!attempt)setAttempt(logical);pendingRef.current=true;setPending(true);setFeedback('');try{const result=await submitMatchIntent({matchId:match.id,expectedVersion:match.version,intentId:logical.intentId,intent:logical.intent});applyMatch(result.match);playGameSound(intent.type==='PLACE_TILE'?'tile':intent.type==='PLACE_MEEPLE'?'meeple':'turn');}catch(reason){const error=reason as {code?:string;status?:number};if(error.code==='VERSION_CONFLICT'||error.code==='TURN_EXPIRED'){setDrafts(EMPTY_ONLINE_DRAFTS);setAttempt(null);setSkipConfirm(false);try{setMatch(await getMatch(match.id));if(error.code==='TURN_EXPIRED')void pumpMatch(match.id);}finally{setFeedback(error.code==='TURN_EXPIRED'?'Время хода истекло':'');}}else setFeedback(error.status&&error.status>=500?'Сервер временно недоступен':'Нет связи с сервером. Можно повторить действие.');}finally{pendingRef.current=false;setPending(false);}};
 const selectMeeple=(target:MeeplePlacement)=>{if(!myTurn||pending)return;setAttempt(current=>attemptAfterMeepleDraftChange(current,drafts.meepleDraft,target));setDrafts(current=>({...current,meepleDraft:target}));};
 const endTurn=()=>{const safety=shouldPromptSkipMeeple(snapshot.derived.legalMeeplePlacements.length,available,drafts.meepleDraft);if(safety==='blocked'){setFeedback('Сначала поставьте человечка или отмените выбор.');return;}if(safety==='prompt'){setSkipConfirm(true);return;}void send({type:'END_TURN'});};
 const playerName=snapshot.game.players.find(p=>p.id===activeId)?.name??'—';
 return <main className="online-game online-game--v2 online-game--v3 online-game--v4">
  <header className="online-game__topbar">
   <div className="online-game__left-tools">
    <button className="chat-trigger" aria-label="Открыть чат" aria-pressed={chatOpen} onClick={()=>setChatOpen(value=>!value)}><SimpleChatGlyph/></button>
    <span className="online-game__deck-count" title="Карт осталось"><GameIcon name="map"/><b>{remainingTiles}</b></span>
   </div>
   <section className="online-game__players" aria-label="Два лидера по очкам">{visiblePlayers.map(({player:p,index,score})=><div className={index===snapshot.game.currentPlayerIndex?'is-current':''} key={p.id}><MeepleSprite className="online-game__player-meeple" color={p.color} size={25}/><span><strong>{index===0&&<span className="host-crown" title="Хозяин лобби"><GameIcon name="crown"/></span>}{p.name}</strong><small><b>{score}</b> очков · {availableMeeples(match,p.id)} мип.</small>{deltas[p.id]&&<em>+{deltas[p.id]}</em>}</span></div>)}</section>
   <div className="online-game__top-actions">{rankedPlayers.length>2&&<button className="online-game__ranking-toggle" aria-label={playersExpanded?'Скрыть остальных игроков':'Показать остальных игроков'} aria-expanded={playersExpanded} onClick={()=>setPlayersExpanded(value=>!value)}><GameIcon name="users"/><small>{playersExpanded?'×':`+${rankedPlayers.length-2}`}</small></button>}<button className="online-game__exit" aria-label="Выйти из игры" onClick={onExit}><GameIcon name="close"/></button></div>
  </header>
  {playersExpanded&&<section className="online-game__standings" aria-label="Рейтинг игроков">{rankedPlayers.map(({player:p,index,score},rank)=><div className={index===snapshot.game.currentPlayerIndex?'is-current':''} key={p.id}><b>{rank+1}</b><MeepleSprite color={p.color} size={24}/><span>{p.name}</span><strong>{score}</strong></div>)}</section>}
  <OnlineTurnHud deadline={statusFinished?null:match.turnDeadlineAt} label={statusFinished?'Игра окончена':botTurn?'Бот думает…':myTurn?'Ваш ход':`Ход: ${playerName}`} connection={connection} onExpired={requestPump}/>{turnNotice&&<div className="turn-change-banner" role="status">{turnNotice}</div>}
  <section className="online-game__viewport" ref={viewportRef}><div className="online-game__canvas" style={{transform:`translate(${camera.camera.offsetX}px,${camera.camera.offsetY}px) scale(${camera.camera.scale})`}} {...camera.handlers}><div className="online-game__board" style={{width:projection.width,height:projection.height}}>
   {boardTiles.map(tile=><div className={`online-game__tile${snapshot.game.lastPlacedTile?.position.x===tile.position.x&&snapshot.game.lastPlacedTile.position.y===tile.position.y?' is-last':''}`} key={`${tile.position.x},${tile.position.y}`} style={{left:(tile.position.x+projection.originX)*CELL,top:(tile.position.y+projection.originY)*CELL}}><TileRenderer definition={getTileDefinition(tile.definitionId)} rotation={tile.rotation} size={CELL}/></div>)}
   {snapshot.game.meeples.filter(m=>m.position&&m.placement).map(m=>{const a=anchorForPlacement(m.placement!),owner=snapshot.game.players.find(p=>p.id===m.playerId);return <span className="online-game__meeple" key={m.id} style={{left:(m.position!.x+projection.originX)*CELL+a.x*CELL/100,top:(m.position!.y+projection.originY)*CELL+a.y*CELL/100}}><MeepleSprite color={owner?.color??'black'} size={25}/></span>})}
   {myTurn&&!drafts.tileDraft&&snapshot.flow.phase==='TILE_IN_HAND'&&snapshot.derived.legalTilePlacementOptions.map(option=><button className="online-game__legal" aria-label={`Выбрать клетку ${option.position.x}, ${option.position.y}`} key={`${option.position.x},${option.position.y}`} style={{left:(option.position.x+projection.originX)*CELL,top:(option.position.y+projection.originY)*CELL}} onClick={()=>{const next=selectTileDraft(match,option.position);setAttempt(current=>attemptAfterTileDraftChange(current,drafts.tileDraft,next));setDrafts({tileDraft:next,meepleDraft:null});}}><span/></button>)}
   {drafts.tileDraft&&snapshot.game.drawnTileDefinitionId&&<button disabled={pending} className="online-game__tile online-game__draft-tile" aria-label="Повернуть карту" style={{left:(drafts.tileDraft.position.x+projection.originX)*CELL,top:(drafts.tileDraft.position.y+projection.originY)*CELL}} onClick={()=>{const next=rotateTileDraft(match,drafts.tileDraft!);setAttempt(current=>attemptAfterTileDraftChange(current,drafts.tileDraft,next));setDrafts(current=>({...current,tileDraft:next}));}}><TileRenderer definition={getTileDefinition(snapshot.game.drawnTileDefinitionId)} rotation={drafts.tileDraft.rotation} size={CELL}/><span className="online-game__rotate-badge"><GameIcon name="rotate"/></span></button>}
   {myTurn&&['TILE_PLACED','MEEPLE_SELECTION'].includes(snapshot.flow.phase)&&snapshot.game.lastPlacedTile&&available>0&&snapshot.derived.legalMeeplePlacements.map(target=>{const a=anchorForPlacement(target),pos=snapshot.game.lastPlacedTile!.position,selected=Boolean(drafts.meepleDraft&&targetKey(drafts.meepleDraft)===targetKey(target));return <button disabled={pending} className={`online-game__meeple-target${selected?' is-selected':''}`} aria-label={`Поставить человечка на ${featureLabel(target)}`} title={`Поставить на ${featureLabel(target)}`} key={targetKey(target)} style={{left:(pos.x+projection.originX)*CELL+a.x*CELL/100,top:(pos.y+projection.originY)*CELL+a.y*CELL/100}} onClick={()=>selectMeeple(target)}><MeepleSprite className="online-game__meeple-preview" color={myColor} ghost={!selected} size={27}/></button>})}
  </div></div><div className="online-game__camera"><button aria-label="Приблизить" onClick={camera.zoomIn}><GameIcon name="plus"/></button><button aria-label="Отдалить" onClick={camera.zoomOut}><GameIcon name="minus"/></button><button aria-label="Вписать поле" onClick={camera.fitContent}><GameIcon name="target"/></button></div></section>
  {feedback&&<p className="online-game__feedback">{feedback}</p>}
  <footer className="online-game__controls"><div className={`online-game__meeple-count${available===0?' is-inactive':''}`} aria-label={`Осталось человечков: ${available}`}><span className="online-game__meeple-token"><MeepleSprite color={myColor} size={46}/><b>{available}</b></span></div><div className="online-game__hand">{snapshot.game.drawnTileDefinitionId&&onlineHandVisible(snapshot.flow.phase,Boolean(drafts.tileDraft))&&<TileRenderer definition={getTileDefinition(snapshot.game.drawnTileDefinitionId)} rotation={0} size={82}/>}</div><div className="online-game__actions">{drafts.tileDraft?<><button disabled={pending} onClick={()=>{setDrafts(EMPTY_ONLINE_DRAFTS);setAttempt(null)}}>Отмена</button><button className="primary" disabled={pending} onClick={()=>void send(tileIntent(drafts.tileDraft!))}>{pending?'Отправка…':'Установить карту'}</button></>:drafts.meepleDraft?<><button disabled={pending} onClick={()=>{setDrafts(current=>({...current,meepleDraft:null}));setAttempt(null)}}>Отмена</button><button className="primary" disabled={pending} onClick={()=>void send({type:'PLACE_MEEPLE',...drafts.meepleDraft!})}>Поставить человечка</button></>:myTurn&&['TILE_PLACED','MEEPLE_SELECTION'].includes(snapshot.flow.phase)?<button className="primary" disabled={pending||statusFinished} onClick={endTurn}><GameIcon name="check"/>Закончить ход</button>:<span>{myTurn?'Выберите место':'Ожидание хода'}</span>}{attempt&&!pending&&<button className="retry" onClick={()=>void send(attempt.intent)}><GameIcon name="retry"/>Повторить</button>}</div></footer>
  {skipConfirm&&<div className="online-game__dialog" role="dialog" aria-modal="true"><section><h2>Закончить ход без человечка?</h2><button onClick={()=>setSkipConfirm(false)}>Отмена</button><button className="primary" onClick={()=>{setSkipConfirm(false);void send({type:'END_TURN'})}}><GameIcon name="check"/>Закончить</button></section></div>}
  {chatOpen&&<OnlineMatchChat lobbyId={match.lobbyId} onClose={()=>setChatOpen(false)}/>} 
  {statusFinished&&<section className="online-game__finished" role="dialog" aria-modal="true"><h2>Игра окончена</h2>{snapshot.game.players.slice().sort((a,b)=>(snapshot.game.scores[b.id]??0)-(snapshot.game.scores[a.id]??0)).map((p,index)=><p className={index===0?'is-winner':''} key={p.id}><span>{index+1}. {index===0&&<GameIcon name="crown"/>}{p.name}</span><b>{snapshot.game.scores[p.id]??0}</b></p>)}<button className="primary" onClick={onExit}><GameIcon name="home"/>В меню</button></section>}
 </main>;
}
